// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsEicm6UOtJEznFf4yDEmPbhALTkKrDmM',
    appId: '1:830240829716:web:1146cc2f787c2e0e011201',
    messagingSenderId: '830240829716',
    projectId: 'fir-demo-d5c67',
    authDomain: 'fir-demo-d5c67.firebaseapp.com',
    storageBucket: 'fir-demo-d5c67.firebasestorage.app',
    measurementId: 'G-JBN9XCZVQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuhKCw-6brlILl98AyRu1Z7coHUAwo2wM',
    appId: '1:830240829716:android:68d5d94fe5ceedb0011201',
    messagingSenderId: '830240829716',
    projectId: 'fir-demo-d5c67',
    storageBucket: 'fir-demo-d5c67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUuE6l2-LTovercrlqAMkEak1QSubQk0c',
    appId: '1:830240829716:ios:6aed95ce01bd73d4011201',
    messagingSenderId: '830240829716',
    projectId: 'fir-demo-d5c67',
    storageBucket: 'fir-demo-d5c67.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUuE6l2-LTovercrlqAMkEak1QSubQk0c',
    appId: '1:830240829716:ios:6aed95ce01bd73d4011201',
    messagingSenderId: '830240829716',
    projectId: 'fir-demo-d5c67',
    storageBucket: 'fir-demo-d5c67.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsEicm6UOtJEznFf4yDEmPbhALTkKrDmM',
    appId: '1:830240829716:web:83d467666b6b4d6d011201',
    messagingSenderId: '830240829716',
    projectId: 'fir-demo-d5c67',
    authDomain: 'fir-demo-d5c67.firebaseapp.com',
    storageBucket: 'fir-demo-d5c67.firebasestorage.app',
    measurementId: 'G-KQPB8Y9FJT',
  );
}
